pipeline{
    agent any
    stages{
        stage("CPU Details"){
            steps{
                sh 'lscpu'
            }
        }
        stage("Memory Details"){
            steps{
                sh 'free -h'
            }
        }
        stage("IP Address"){
            steps{
                sh 'hostname -I'
            }
        }
        stage("Disk Usage"){
            steps{
                sh 'df -h'
            }
        }
        stage("No of CPUs"){
            steps{
                sh 'nproc'
            }
        }
    }
}
